video_dir: "/Users/hrithikyash/Downloads/Project MASbots "
output_dir: "./data/processed"
figures_dir: "./reports/figures"
interpolation_gap_max_frames: 5
radius_threshold_px: 80
dwell_threshold_sec: 2.0

